// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.15.8
// source: zomato.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ZomatoDatabaseCrudClient is the client API for ZomatoDatabaseCrud service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ZomatoDatabaseCrudClient interface {
	CreateUser(ctx context.Context, in *NewUser, opts ...grpc.CallOption) (*User, error)
	ReadUser(ctx context.Context, in *VoidUserRequest, opts ...grpc.CallOption) (*AllUsers, error)
	UpdateUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*User, error)
}

type zomatoDatabaseCrudClient struct {
	cc grpc.ClientConnInterface
}

func NewZomatoDatabaseCrudClient(cc grpc.ClientConnInterface) ZomatoDatabaseCrudClient {
	return &zomatoDatabaseCrudClient{cc}
}

func (c *zomatoDatabaseCrudClient) CreateUser(ctx context.Context, in *NewUser, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/zomatoDB.ZomatoDatabaseCrud/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zomatoDatabaseCrudClient) ReadUser(ctx context.Context, in *VoidUserRequest, opts ...grpc.CallOption) (*AllUsers, error) {
	out := new(AllUsers)
	err := c.cc.Invoke(ctx, "/zomatoDB.ZomatoDatabaseCrud/ReadUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zomatoDatabaseCrudClient) UpdateUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/zomatoDB.ZomatoDatabaseCrud/UpdateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ZomatoDatabaseCrudServer is the server API for ZomatoDatabaseCrud service.
// All implementations must embed UnimplementedZomatoDatabaseCrudServer
// for forward compatibility
type ZomatoDatabaseCrudServer interface {
	CreateUser(context.Context, *NewUser) (*User, error)
	ReadUser(context.Context, *VoidUserRequest) (*AllUsers, error)
	UpdateUser(context.Context, *User) (*User, error)
	mustEmbedUnimplementedZomatoDatabaseCrudServer()
}

// UnimplementedZomatoDatabaseCrudServer must be embedded to have forward compatible implementations.
type UnimplementedZomatoDatabaseCrudServer struct {
}

func (UnimplementedZomatoDatabaseCrudServer) CreateUser(context.Context, *NewUser) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}
func (UnimplementedZomatoDatabaseCrudServer) ReadUser(context.Context, *VoidUserRequest) (*AllUsers, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadUser not implemented")
}
func (UnimplementedZomatoDatabaseCrudServer) UpdateUser(context.Context, *User) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUser not implemented")
}
func (UnimplementedZomatoDatabaseCrudServer) mustEmbedUnimplementedZomatoDatabaseCrudServer() {}

// UnsafeZomatoDatabaseCrudServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ZomatoDatabaseCrudServer will
// result in compilation errors.
type UnsafeZomatoDatabaseCrudServer interface {
	mustEmbedUnimplementedZomatoDatabaseCrudServer()
}

func RegisterZomatoDatabaseCrudServer(s grpc.ServiceRegistrar, srv ZomatoDatabaseCrudServer) {
	s.RegisterService(&ZomatoDatabaseCrud_ServiceDesc, srv)
}

func _ZomatoDatabaseCrud_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewUser)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZomatoDatabaseCrudServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/zomatoDB.ZomatoDatabaseCrud/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZomatoDatabaseCrudServer).CreateUser(ctx, req.(*NewUser))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZomatoDatabaseCrud_ReadUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VoidUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZomatoDatabaseCrudServer).ReadUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/zomatoDB.ZomatoDatabaseCrud/ReadUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZomatoDatabaseCrudServer).ReadUser(ctx, req.(*VoidUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZomatoDatabaseCrud_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZomatoDatabaseCrudServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/zomatoDB.ZomatoDatabaseCrud/UpdateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZomatoDatabaseCrudServer).UpdateUser(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

// ZomatoDatabaseCrud_ServiceDesc is the grpc.ServiceDesc for ZomatoDatabaseCrud service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ZomatoDatabaseCrud_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "zomatoDB.ZomatoDatabaseCrud",
	HandlerType: (*ZomatoDatabaseCrudServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _ZomatoDatabaseCrud_CreateUser_Handler,
		},
		{
			MethodName: "ReadUser",
			Handler:    _ZomatoDatabaseCrud_ReadUser_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _ZomatoDatabaseCrud_UpdateUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "zomato.proto",
}
