// Code generated by protoc-gen-go. DO NOT EDIT.
// source: zomato.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Phone                string   `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`
	Address              string   `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf5f31cd82a50922, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *User) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type NewUser struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Phone                string   `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`
	Address              string   `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewUser) Reset()         { *m = NewUser{} }
func (m *NewUser) String() string { return proto.CompactTextString(m) }
func (*NewUser) ProtoMessage()    {}
func (*NewUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf5f31cd82a50922, []int{1}
}

func (m *NewUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewUser.Unmarshal(m, b)
}
func (m *NewUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewUser.Marshal(b, m, deterministic)
}
func (m *NewUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewUser.Merge(m, src)
}
func (m *NewUser) XXX_Size() int {
	return xxx_messageInfo_NewUser.Size(m)
}
func (m *NewUser) XXX_DiscardUnknown() {
	xxx_messageInfo_NewUser.DiscardUnknown(m)
}

var xxx_messageInfo_NewUser proto.InternalMessageInfo

func (m *NewUser) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *NewUser) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NewUser) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *NewUser) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *NewUser) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type UserOrder struct {
	OrderItems           []*OrderItem `protobuf:"bytes,1,rep,name=orderItems,proto3" json:"orderItems,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *UserOrder) Reset()         { *m = UserOrder{} }
func (m *UserOrder) String() string { return proto.CompactTextString(m) }
func (*UserOrder) ProtoMessage()    {}
func (*UserOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf5f31cd82a50922, []int{2}
}

func (m *UserOrder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserOrder.Unmarshal(m, b)
}
func (m *UserOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserOrder.Marshal(b, m, deterministic)
}
func (m *UserOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserOrder.Merge(m, src)
}
func (m *UserOrder) XXX_Size() int {
	return xxx_messageInfo_UserOrder.Size(m)
}
func (m *UserOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_UserOrder.DiscardUnknown(m)
}

var xxx_messageInfo_UserOrder proto.InternalMessageInfo

func (m *UserOrder) GetOrderItems() []*OrderItem {
	if m != nil {
		return m.OrderItems
	}
	return nil
}

type AllUsers struct {
	AllUsers             []*User  `protobuf:"bytes,1,rep,name=AllUsers,proto3" json:"AllUsers,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AllUsers) Reset()         { *m = AllUsers{} }
func (m *AllUsers) String() string { return proto.CompactTextString(m) }
func (*AllUsers) ProtoMessage()    {}
func (*AllUsers) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf5f31cd82a50922, []int{3}
}

func (m *AllUsers) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AllUsers.Unmarshal(m, b)
}
func (m *AllUsers) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AllUsers.Marshal(b, m, deterministic)
}
func (m *AllUsers) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllUsers.Merge(m, src)
}
func (m *AllUsers) XXX_Size() int {
	return xxx_messageInfo_AllUsers.Size(m)
}
func (m *AllUsers) XXX_DiscardUnknown() {
	xxx_messageInfo_AllUsers.DiscardUnknown(m)
}

var xxx_messageInfo_AllUsers proto.InternalMessageInfo

func (m *AllUsers) GetAllUsers() []*User {
	if m != nil {
		return m.AllUsers
	}
	return nil
}

type VoidUserRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VoidUserRequest) Reset()         { *m = VoidUserRequest{} }
func (m *VoidUserRequest) String() string { return proto.CompactTextString(m) }
func (*VoidUserRequest) ProtoMessage()    {}
func (*VoidUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf5f31cd82a50922, []int{4}
}

func (m *VoidUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VoidUserRequest.Unmarshal(m, b)
}
func (m *VoidUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VoidUserRequest.Marshal(b, m, deterministic)
}
func (m *VoidUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VoidUserRequest.Merge(m, src)
}
func (m *VoidUserRequest) XXX_Size() int {
	return xxx_messageInfo_VoidUserRequest.Size(m)
}
func (m *VoidUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VoidUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VoidUserRequest proto.InternalMessageInfo

type OrderItem struct {
	DishId               int64    `protobuf:"varint,1,opt,name=DishId,proto3" json:"DishId,omitempty"`
	Quantity             int64    `protobuf:"varint,2,opt,name=Quantity,proto3" json:"Quantity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderItem) Reset()         { *m = OrderItem{} }
func (m *OrderItem) String() string { return proto.CompactTextString(m) }
func (*OrderItem) ProtoMessage()    {}
func (*OrderItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf5f31cd82a50922, []int{5}
}

func (m *OrderItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderItem.Unmarshal(m, b)
}
func (m *OrderItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderItem.Marshal(b, m, deterministic)
}
func (m *OrderItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderItem.Merge(m, src)
}
func (m *OrderItem) XXX_Size() int {
	return xxx_messageInfo_OrderItem.Size(m)
}
func (m *OrderItem) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderItem.DiscardUnknown(m)
}

var xxx_messageInfo_OrderItem proto.InternalMessageInfo

func (m *OrderItem) GetDishId() int64 {
	if m != nil {
		return m.DishId
	}
	return 0
}

func (m *OrderItem) GetQuantity() int64 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

type NewRestaurant struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Address              string   `protobuf:"bytes,2,opt,name=Address,proto3" json:"Address,omitempty"`
	Timings              string   `protobuf:"bytes,3,opt,name=Timings,proto3" json:"Timings,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=Email,proto3" json:"Email,omitempty"`
	Password             string   `protobuf:"bytes,5,opt,name=Password,proto3" json:"Password,omitempty"`
	IsActive             bool     `protobuf:"varint,6,opt,name=IsActive,proto3" json:"IsActive,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewRestaurant) Reset()         { *m = NewRestaurant{} }
func (m *NewRestaurant) String() string { return proto.CompactTextString(m) }
func (*NewRestaurant) ProtoMessage()    {}
func (*NewRestaurant) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf5f31cd82a50922, []int{6}
}

func (m *NewRestaurant) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewRestaurant.Unmarshal(m, b)
}
func (m *NewRestaurant) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewRestaurant.Marshal(b, m, deterministic)
}
func (m *NewRestaurant) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewRestaurant.Merge(m, src)
}
func (m *NewRestaurant) XXX_Size() int {
	return xxx_messageInfo_NewRestaurant.Size(m)
}
func (m *NewRestaurant) XXX_DiscardUnknown() {
	xxx_messageInfo_NewRestaurant.DiscardUnknown(m)
}

var xxx_messageInfo_NewRestaurant proto.InternalMessageInfo

func (m *NewRestaurant) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NewRestaurant) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *NewRestaurant) GetTimings() string {
	if m != nil {
		return m.Timings
	}
	return ""
}

func (m *NewRestaurant) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *NewRestaurant) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *NewRestaurant) GetIsActive() bool {
	if m != nil {
		return m.IsActive
	}
	return false
}

type Restaurant struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Address              string   `protobuf:"bytes,2,opt,name=Address,proto3" json:"Address,omitempty"`
	Timings              string   `protobuf:"bytes,3,opt,name=Timings,proto3" json:"Timings,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=Email,proto3" json:"Email,omitempty"`
	Password             string   `protobuf:"bytes,5,opt,name=Password,proto3" json:"Password,omitempty"`
	IsActive             bool     `protobuf:"varint,6,opt,name=IsActive,proto3" json:"IsActive,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Restaurant) Reset()         { *m = Restaurant{} }
func (m *Restaurant) String() string { return proto.CompactTextString(m) }
func (*Restaurant) ProtoMessage()    {}
func (*Restaurant) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf5f31cd82a50922, []int{7}
}

func (m *Restaurant) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Restaurant.Unmarshal(m, b)
}
func (m *Restaurant) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Restaurant.Marshal(b, m, deterministic)
}
func (m *Restaurant) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Restaurant.Merge(m, src)
}
func (m *Restaurant) XXX_Size() int {
	return xxx_messageInfo_Restaurant.Size(m)
}
func (m *Restaurant) XXX_DiscardUnknown() {
	xxx_messageInfo_Restaurant.DiscardUnknown(m)
}

var xxx_messageInfo_Restaurant proto.InternalMessageInfo

func (m *Restaurant) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Restaurant) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Restaurant) GetTimings() string {
	if m != nil {
		return m.Timings
	}
	return ""
}

func (m *Restaurant) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Restaurant) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *Restaurant) GetIsActive() bool {
	if m != nil {
		return m.IsActive
	}
	return false
}

type NewDish struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=Description,proto3" json:"Description,omitempty"`
	Image                string   `protobuf:"bytes,3,opt,name=Image,proto3" json:"Image,omitempty"`
	Price                int64    `protobuf:"varint,4,opt,name=Price,proto3" json:"Price,omitempty"`
	RestaurantId         int64    `protobuf:"varint,5,opt,name=RestaurantId,proto3" json:"RestaurantId,omitempty"`
	IsAvailable          bool     `protobuf:"varint,6,opt,name=IsAvailable,proto3" json:"IsAvailable,omitempty"`
	IsVeg                bool     `protobuf:"varint,7,opt,name=IsVeg,proto3" json:"IsVeg,omitempty"`
	Cuisine              string   `protobuf:"bytes,8,opt,name=Cuisine,proto3" json:"Cuisine,omitempty"`
	Category             string   `protobuf:"bytes,9,opt,name=Category,proto3" json:"Category,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewDish) Reset()         { *m = NewDish{} }
func (m *NewDish) String() string { return proto.CompactTextString(m) }
func (*NewDish) ProtoMessage()    {}
func (*NewDish) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf5f31cd82a50922, []int{8}
}

func (m *NewDish) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewDish.Unmarshal(m, b)
}
func (m *NewDish) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewDish.Marshal(b, m, deterministic)
}
func (m *NewDish) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewDish.Merge(m, src)
}
func (m *NewDish) XXX_Size() int {
	return xxx_messageInfo_NewDish.Size(m)
}
func (m *NewDish) XXX_DiscardUnknown() {
	xxx_messageInfo_NewDish.DiscardUnknown(m)
}

var xxx_messageInfo_NewDish proto.InternalMessageInfo

func (m *NewDish) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NewDish) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *NewDish) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *NewDish) GetPrice() int64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *NewDish) GetRestaurantId() int64 {
	if m != nil {
		return m.RestaurantId
	}
	return 0
}

func (m *NewDish) GetIsAvailable() bool {
	if m != nil {
		return m.IsAvailable
	}
	return false
}

func (m *NewDish) GetIsVeg() bool {
	if m != nil {
		return m.IsVeg
	}
	return false
}

func (m *NewDish) GetCuisine() string {
	if m != nil {
		return m.Cuisine
	}
	return ""
}

func (m *NewDish) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

type Dish struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=Description,proto3" json:"Description,omitempty"`
	Image                string   `protobuf:"bytes,3,opt,name=Image,proto3" json:"Image,omitempty"`
	Price                int64    `protobuf:"varint,4,opt,name=Price,proto3" json:"Price,omitempty"`
	RestaurantId         int64    `protobuf:"varint,5,opt,name=RestaurantId,proto3" json:"RestaurantId,omitempty"`
	IsAvailable          bool     `protobuf:"varint,6,opt,name=IsAvailable,proto3" json:"IsAvailable,omitempty"`
	IsVeg                bool     `protobuf:"varint,7,opt,name=IsVeg,proto3" json:"IsVeg,omitempty"`
	Cuisine              string   `protobuf:"bytes,8,opt,name=Cuisine,proto3" json:"Cuisine,omitempty"`
	Category             string   `protobuf:"bytes,9,opt,name=Category,proto3" json:"Category,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Dish) Reset()         { *m = Dish{} }
func (m *Dish) String() string { return proto.CompactTextString(m) }
func (*Dish) ProtoMessage()    {}
func (*Dish) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf5f31cd82a50922, []int{9}
}

func (m *Dish) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Dish.Unmarshal(m, b)
}
func (m *Dish) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Dish.Marshal(b, m, deterministic)
}
func (m *Dish) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Dish.Merge(m, src)
}
func (m *Dish) XXX_Size() int {
	return xxx_messageInfo_Dish.Size(m)
}
func (m *Dish) XXX_DiscardUnknown() {
	xxx_messageInfo_Dish.DiscardUnknown(m)
}

var xxx_messageInfo_Dish proto.InternalMessageInfo

func (m *Dish) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Dish) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Dish) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *Dish) GetPrice() int64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Dish) GetRestaurantId() int64 {
	if m != nil {
		return m.RestaurantId
	}
	return 0
}

func (m *Dish) GetIsAvailable() bool {
	if m != nil {
		return m.IsAvailable
	}
	return false
}

func (m *Dish) GetIsVeg() bool {
	if m != nil {
		return m.IsVeg
	}
	return false
}

func (m *Dish) GetCuisine() string {
	if m != nil {
		return m.Cuisine
	}
	return ""
}

func (m *Dish) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

type VoidDishResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VoidDishResponse) Reset()         { *m = VoidDishResponse{} }
func (m *VoidDishResponse) String() string { return proto.CompactTextString(m) }
func (*VoidDishResponse) ProtoMessage()    {}
func (*VoidDishResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf5f31cd82a50922, []int{10}
}

func (m *VoidDishResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VoidDishResponse.Unmarshal(m, b)
}
func (m *VoidDishResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VoidDishResponse.Marshal(b, m, deterministic)
}
func (m *VoidDishResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VoidDishResponse.Merge(m, src)
}
func (m *VoidDishResponse) XXX_Size() int {
	return xxx_messageInfo_VoidDishResponse.Size(m)
}
func (m *VoidDishResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VoidDishResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VoidDishResponse proto.InternalMessageInfo

type RestaurantMenuRequest struct {
	RestaurantID         int64    `protobuf:"varint,1,opt,name=RestaurantID,proto3" json:"RestaurantID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RestaurantMenuRequest) Reset()         { *m = RestaurantMenuRequest{} }
func (m *RestaurantMenuRequest) String() string { return proto.CompactTextString(m) }
func (*RestaurantMenuRequest) ProtoMessage()    {}
func (*RestaurantMenuRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf5f31cd82a50922, []int{11}
}

func (m *RestaurantMenuRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RestaurantMenuRequest.Unmarshal(m, b)
}
func (m *RestaurantMenuRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RestaurantMenuRequest.Marshal(b, m, deterministic)
}
func (m *RestaurantMenuRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RestaurantMenuRequest.Merge(m, src)
}
func (m *RestaurantMenuRequest) XXX_Size() int {
	return xxx_messageInfo_RestaurantMenuRequest.Size(m)
}
func (m *RestaurantMenuRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RestaurantMenuRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RestaurantMenuRequest proto.InternalMessageInfo

func (m *RestaurantMenuRequest) GetRestaurantID() int64 {
	if m != nil {
		return m.RestaurantID
	}
	return 0
}

type Menu struct {
	Dishes               []*Dish  `protobuf:"bytes,1,rep,name=dishes,proto3" json:"dishes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Menu) Reset()         { *m = Menu{} }
func (m *Menu) String() string { return proto.CompactTextString(m) }
func (*Menu) ProtoMessage()    {}
func (*Menu) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf5f31cd82a50922, []int{12}
}

func (m *Menu) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Menu.Unmarshal(m, b)
}
func (m *Menu) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Menu.Marshal(b, m, deterministic)
}
func (m *Menu) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Menu.Merge(m, src)
}
func (m *Menu) XXX_Size() int {
	return xxx_messageInfo_Menu.Size(m)
}
func (m *Menu) XXX_DiscardUnknown() {
	xxx_messageInfo_Menu.DiscardUnknown(m)
}

var xxx_messageInfo_Menu proto.InternalMessageInfo

func (m *Menu) GetDishes() []*Dish {
	if m != nil {
		return m.Dishes
	}
	return nil
}

type NewAgent struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Phone                string   `protobuf:"bytes,2,opt,name=Phone,proto3" json:"Phone,omitempty"`
	Address              string   `protobuf:"bytes,3,opt,name=Address,proto3" json:"Address,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=Email,proto3" json:"Email,omitempty"`
	IsActive             bool     `protobuf:"varint,5,opt,name=IsActive,proto3" json:"IsActive,omitempty"`
	CurrentOrderId       int64    `protobuf:"varint,6,opt,name=CurrentOrderId,proto3" json:"CurrentOrderId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewAgent) Reset()         { *m = NewAgent{} }
func (m *NewAgent) String() string { return proto.CompactTextString(m) }
func (*NewAgent) ProtoMessage()    {}
func (*NewAgent) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf5f31cd82a50922, []int{13}
}

func (m *NewAgent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewAgent.Unmarshal(m, b)
}
func (m *NewAgent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewAgent.Marshal(b, m, deterministic)
}
func (m *NewAgent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewAgent.Merge(m, src)
}
func (m *NewAgent) XXX_Size() int {
	return xxx_messageInfo_NewAgent.Size(m)
}
func (m *NewAgent) XXX_DiscardUnknown() {
	xxx_messageInfo_NewAgent.DiscardUnknown(m)
}

var xxx_messageInfo_NewAgent proto.InternalMessageInfo

func (m *NewAgent) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NewAgent) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *NewAgent) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *NewAgent) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *NewAgent) GetIsActive() bool {
	if m != nil {
		return m.IsActive
	}
	return false
}

func (m *NewAgent) GetCurrentOrderId() int64 {
	if m != nil {
		return m.CurrentOrderId
	}
	return 0
}

type Agent struct {
	Id                   int64    `protobuf:"varint,7,opt,name=Id,proto3" json:"Id,omitempty"`
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Phone                string   `protobuf:"bytes,2,opt,name=Phone,proto3" json:"Phone,omitempty"`
	Address              string   `protobuf:"bytes,3,opt,name=Address,proto3" json:"Address,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=Email,proto3" json:"Email,omitempty"`
	IsActive             bool     `protobuf:"varint,5,opt,name=IsActive,proto3" json:"IsActive,omitempty"`
	CurrentOrderId       int64    `protobuf:"varint,6,opt,name=CurrentOrderId,proto3" json:"CurrentOrderId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Agent) Reset()         { *m = Agent{} }
func (m *Agent) String() string { return proto.CompactTextString(m) }
func (*Agent) ProtoMessage()    {}
func (*Agent) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf5f31cd82a50922, []int{14}
}

func (m *Agent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Agent.Unmarshal(m, b)
}
func (m *Agent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Agent.Marshal(b, m, deterministic)
}
func (m *Agent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Agent.Merge(m, src)
}
func (m *Agent) XXX_Size() int {
	return xxx_messageInfo_Agent.Size(m)
}
func (m *Agent) XXX_DiscardUnknown() {
	xxx_messageInfo_Agent.DiscardUnknown(m)
}

var xxx_messageInfo_Agent proto.InternalMessageInfo

func (m *Agent) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Agent) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Agent) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *Agent) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Agent) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Agent) GetIsActive() bool {
	if m != nil {
		return m.IsActive
	}
	return false
}

func (m *Agent) GetCurrentOrderId() int64 {
	if m != nil {
		return m.CurrentOrderId
	}
	return 0
}

type AgentStatus struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	IsActive             bool     `protobuf:"varint,2,opt,name=IsActive,proto3" json:"IsActive,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AgentStatus) Reset()         { *m = AgentStatus{} }
func (m *AgentStatus) String() string { return proto.CompactTextString(m) }
func (*AgentStatus) ProtoMessage()    {}
func (*AgentStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf5f31cd82a50922, []int{15}
}

func (m *AgentStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgentStatus.Unmarshal(m, b)
}
func (m *AgentStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgentStatus.Marshal(b, m, deterministic)
}
func (m *AgentStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgentStatus.Merge(m, src)
}
func (m *AgentStatus) XXX_Size() int {
	return xxx_messageInfo_AgentStatus.Size(m)
}
func (m *AgentStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_AgentStatus.DiscardUnknown(m)
}

var xxx_messageInfo_AgentStatus proto.InternalMessageInfo

func (m *AgentStatus) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AgentStatus) GetIsActive() bool {
	if m != nil {
		return m.IsActive
	}
	return false
}

type OrderID struct {
	Id                   int64    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderID) Reset()         { *m = OrderID{} }
func (m *OrderID) String() string { return proto.CompactTextString(m) }
func (*OrderID) ProtoMessage()    {}
func (*OrderID) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf5f31cd82a50922, []int{16}
}

func (m *OrderID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderID.Unmarshal(m, b)
}
func (m *OrderID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderID.Marshal(b, m, deterministic)
}
func (m *OrderID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderID.Merge(m, src)
}
func (m *OrderID) XXX_Size() int {
	return xxx_messageInfo_OrderID.Size(m)
}
func (m *OrderID) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderID.DiscardUnknown(m)
}

var xxx_messageInfo_OrderID proto.InternalMessageInfo

func (m *OrderID) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type AgentOrders struct {
	OrderID              []*OrderID `protobuf:"bytes,1,rep,name=OrderID,proto3" json:"OrderID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *AgentOrders) Reset()         { *m = AgentOrders{} }
func (m *AgentOrders) String() string { return proto.CompactTextString(m) }
func (*AgentOrders) ProtoMessage()    {}
func (*AgentOrders) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf5f31cd82a50922, []int{17}
}

func (m *AgentOrders) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgentOrders.Unmarshal(m, b)
}
func (m *AgentOrders) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgentOrders.Marshal(b, m, deterministic)
}
func (m *AgentOrders) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgentOrders.Merge(m, src)
}
func (m *AgentOrders) XXX_Size() int {
	return xxx_messageInfo_AgentOrders.Size(m)
}
func (m *AgentOrders) XXX_DiscardUnknown() {
	xxx_messageInfo_AgentOrders.DiscardUnknown(m)
}

var xxx_messageInfo_AgentOrders proto.InternalMessageInfo

func (m *AgentOrders) GetOrderID() []*OrderID {
	if m != nil {
		return m.OrderID
	}
	return nil
}

func init() {
	proto.RegisterType((*User)(nil), "zomatoDB.User")
	proto.RegisterType((*NewUser)(nil), "zomatoDB.NewUser")
	proto.RegisterType((*UserOrder)(nil), "zomatoDB.UserOrder")
	proto.RegisterType((*AllUsers)(nil), "zomatoDB.AllUsers")
	proto.RegisterType((*VoidUserRequest)(nil), "zomatoDB.VoidUserRequest")
	proto.RegisterType((*OrderItem)(nil), "zomatoDB.OrderItem")
	proto.RegisterType((*NewRestaurant)(nil), "zomatoDB.NewRestaurant")
	proto.RegisterType((*Restaurant)(nil), "zomatoDB.Restaurant")
	proto.RegisterType((*NewDish)(nil), "zomatoDB.NewDish")
	proto.RegisterType((*Dish)(nil), "zomatoDB.Dish")
	proto.RegisterType((*VoidDishResponse)(nil), "zomatoDB.VoidDishResponse")
	proto.RegisterType((*RestaurantMenuRequest)(nil), "zomatoDB.RestaurantMenuRequest")
	proto.RegisterType((*Menu)(nil), "zomatoDB.Menu")
	proto.RegisterType((*NewAgent)(nil), "zomatoDB.NewAgent")
	proto.RegisterType((*Agent)(nil), "zomatoDB.Agent")
	proto.RegisterType((*AgentStatus)(nil), "zomatoDB.AgentStatus")
	proto.RegisterType((*OrderID)(nil), "zomatoDB.OrderID")
	proto.RegisterType((*AgentOrders)(nil), "zomatoDB.AgentOrders")
}

func init() { proto.RegisterFile("zomato.proto", fileDescriptor_cf5f31cd82a50922) }

var fileDescriptor_cf5f31cd82a50922 = []byte{
	// 869 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe4, 0x56, 0xdd, 0x6e, 0x1b, 0x45,
	0x14, 0xf6, 0x7a, 0x1d, 0xc7, 0x39, 0x69, 0xd3, 0x64, 0xda, 0xc2, 0x76, 0x85, 0xc0, 0x9a, 0x8b,
	0x2a, 0x02, 0xd5, 0x15, 0x2d, 0xea, 0x45, 0xab, 0x8a, 0xba, 0x5e, 0xa8, 0xf6, 0x82, 0xb4, 0x2c,
	0xb4, 0x17, 0xbd, 0x9b, 0x78, 0x8f, 0x9c, 0x11, 0xf6, 0xae, 0x99, 0x99, 0x4d, 0x14, 0x9e, 0x83,
	0x27, 0x40, 0x42, 0xe2, 0x05, 0x78, 0x39, 0x24, 0x24, 0x34, 0x3f, 0xfb, 0xcb, 0xfa, 0x16, 0x55,
	0xe2, 0x26, 0xd9, 0xef, 0x3b, 0x67, 0xf6, 0x7c, 0xf3, 0x9d, 0x3d, 0x33, 0x86, 0x1b, 0xbf, 0xe4,
	0x1b, 0xa6, 0xf2, 0xd9, 0x56, 0xe4, 0x2a, 0x27, 0x13, 0x8b, 0xa2, 0x97, 0x74, 0x0b, 0xa3, 0xb7,
	0x12, 0x05, 0x39, 0x82, 0x21, 0x4f, 0x03, 0x6f, 0xea, 0x9d, 0xfa, 0xc9, 0x90, 0xa7, 0x84, 0xc0,
	0x28, 0x63, 0x1b, 0x0c, 0x86, 0x53, 0xef, 0xf4, 0x20, 0x31, 0xcf, 0xe4, 0x0e, 0xec, 0x6d, 0x2f,
	0xf2, 0x0c, 0x83, 0x3d, 0x43, 0x5a, 0x40, 0x02, 0xd8, 0x67, 0x69, 0x2a, 0x50, 0xca, 0xc0, 0x37,
	0x7c, 0x09, 0x75, 0x3e, 0x6e, 0x18, 0x5f, 0x07, 0x23, 0x9b, 0x6f, 0x00, 0x95, 0xb0, 0x7f, 0x86,
	0x57, 0xff, 0x71, 0xd1, 0x17, 0x70, 0xa0, 0x2b, 0xbe, 0x16, 0x29, 0x0a, 0xf2, 0x18, 0x20, 0xd7,
	0x0f, 0xb1, 0xc2, 0x8d, 0x0c, 0xbc, 0xa9, 0x7f, 0x7a, 0xf8, 0xe8, 0xf6, 0xac, 0xb4, 0x64, 0xf6,
	0xba, 0x8c, 0x25, 0x8d, 0x34, 0xfa, 0x04, 0x26, 0xf3, 0xf5, 0x5a, 0xbf, 0x44, 0x92, 0xcf, 0xeb,
	0x67, 0xb7, 0xfc, 0xa8, 0x5e, 0xae, 0xe9, 0xa4, 0x8a, 0xd3, 0x13, 0xb8, 0xf5, 0x2e, 0xe7, 0xa9,
	0x61, 0xf1, 0xe7, 0x02, 0xa5, 0xa2, 0x5f, 0xc3, 0x41, 0x55, 0x83, 0x7c, 0x04, 0xe3, 0x88, 0xcb,
	0x8b, 0xb8, 0xf4, 0xc1, 0x21, 0x12, 0xc2, 0xe4, 0xfb, 0x82, 0x65, 0x8a, 0xab, 0x6b, 0xe3, 0x87,
	0x9f, 0x54, 0x98, 0xfe, 0xee, 0xc1, 0xcd, 0x33, 0xbc, 0x4a, 0x50, 0x2a, 0x56, 0x08, 0x96, 0x29,
	0xed, 0xdc, 0x99, 0x76, 0xce, 0xb3, 0xce, 0xe9, 0x67, 0xed, 0xd1, 0xdc, 0x79, 0x64, 0x0d, 0x2d,
	0xa1, 0x8e, 0xfc, 0xc8, 0x37, 0x3c, 0x5b, 0x55, 0xee, 0x39, 0xa8, 0xdd, 0xfb, 0xa6, 0xe9, 0x9e,
	0x01, 0x5a, 0xcb, 0x1b, 0x26, 0xe5, 0x55, 0x2e, 0x52, 0xd7, 0x86, 0x0a, 0xeb, 0x58, 0x2c, 0xe7,
	0x4b, 0xc5, 0x2f, 0x31, 0x18, 0x4f, 0xbd, 0xd3, 0x49, 0x52, 0x61, 0xfa, 0x9b, 0x07, 0xf0, 0xc1,
	0x8b, 0xfc, 0xdb, 0x33, 0x1f, 0xa4, 0xb6, 0xbd, 0x57, 0xe1, 0x14, 0x0e, 0x23, 0x94, 0x4b, 0xc1,
	0xb7, 0x8a, 0xe7, 0x99, 0x53, 0xd9, 0xa4, 0xb4, 0x9e, 0x78, 0xc3, 0x56, 0xe8, 0x74, 0x5a, 0xa0,
	0xd9, 0x37, 0x82, 0x2f, 0xd1, 0xa8, 0xf4, 0x13, 0x0b, 0x08, 0x85, 0x1b, 0xb5, 0x23, 0xb1, 0x55,
	0xea, 0x27, 0x2d, 0x4e, 0x57, 0x8c, 0xe5, 0xfc, 0x92, 0xf1, 0x35, 0x3b, 0x5f, 0x97, 0x82, 0x9b,
	0x94, 0xa9, 0x28, 0xdf, 0xe1, 0x2a, 0xd8, 0x37, 0x31, 0x0b, 0xb4, 0x63, 0x8b, 0x82, 0x4b, 0x9e,
	0x61, 0x30, 0xb1, 0x8e, 0x39, 0xa8, 0xf7, 0xbf, 0x60, 0x0a, 0x57, 0xb9, 0xb8, 0x0e, 0x0e, 0xac,
	0x37, 0x25, 0xa6, 0x7f, 0x79, 0x30, 0xfa, 0xdf, 0x6e, 0x9e, 0xc0, 0xb1, 0x9e, 0x4e, 0xbd, 0xff,
	0x04, 0xe5, 0x36, 0xcf, 0x24, 0xd2, 0x67, 0x70, 0xb7, 0x56, 0xf4, 0x1d, 0x66, 0x85, 0x9b, 0xdb,
	0x8e, 0xfc, 0xc8, 0x0d, 0x6c, 0x8b, 0xa3, 0x33, 0x18, 0xe9, 0x25, 0xe4, 0x3e, 0x8c, 0x53, 0x2e,
	0x2f, 0xb0, 0xe7, 0x80, 0x30, 0xc5, 0x5c, 0x94, 0xfe, 0xe1, 0xc1, 0xe4, 0x0c, 0xaf, 0xe6, 0x2b,
	0xdc, 0x31, 0x20, 0xda, 0x49, 0x73, 0xfe, 0x59, 0xef, 0x2d, 0x68, 0x8e, 0x8d, 0xdf, 0x1e, 0x9b,
	0x9d, 0xc3, 0x51, 0x0d, 0xc0, 0x5e, 0x7b, 0x00, 0xc8, 0x7d, 0x38, 0x5a, 0x14, 0x42, 0x60, 0xa6,
	0xec, 0xa9, 0x94, 0x1a, 0xd3, 0xfd, 0xa4, 0xc3, 0xd2, 0x3f, 0x3d, 0xd8, 0xb3, 0x3a, 0x8f, 0x60,
	0x18, 0xa7, 0xc6, 0x7e, 0x3f, 0x19, 0xc6, 0xe9, 0x07, 0xae, 0xfb, 0x39, 0x1c, 0x1a, 0xd9, 0x3f,
	0x28, 0xa6, 0x0a, 0xd9, 0x2b, 0xb6, 0x59, 0x66, 0xd8, 0x39, 0x1f, 0xee, 0xc1, 0xbe, 0x7d, 0x53,
	0xe4, 0xf6, 0xed, 0x95, 0xfb, 0xa6, 0x4f, 0xdd, 0x9b, 0x4d, 0x5c, 0x92, 0x2f, 0xaa, 0x4c, 0xd7,
	0xf4, 0x93, 0xee, 0xa5, 0x12, 0x25, 0x65, 0xc6, 0xa3, 0x5f, 0xc7, 0x40, 0xde, 0xdb, 0x28, 0x53,
	0xec, 0x9c, 0x49, 0x5c, 0x88, 0x22, 0x25, 0x5f, 0x02, 0x2c, 0x04, 0x32, 0x85, 0xe6, 0x82, 0x6c,
	0xbc, 0xc0, 0xdd, 0x99, 0x61, 0xe7, 0xa6, 0xa1, 0x03, 0x32, 0x03, 0x78, 0xbb, 0x4d, 0xcb, 0x25,
	0x9d, 0x78, 0x4f, 0xfe, 0x33, 0x98, 0xbc, 0x42, 0x65, 0x6f, 0xb2, 0x7b, 0x75, 0xb4, 0x73, 0x4b,
	0x85, 0xa4, 0x0e, 0x55, 0x97, 0xd9, 0x80, 0x3c, 0x81, 0x9b, 0x6e, 0xb1, 0xdb, 0x74, 0xb7, 0xde,
	0xed, 0x36, 0x36, 0x59, 0x74, 0x40, 0x16, 0x70, 0x6c, 0xf7, 0xd5, 0xb8, 0x0f, 0x3e, 0x6e, 0xed,
	0xae, 0x0e, 0x84, 0x77, 0xea, 0x40, 0xcd, 0xd2, 0x01, 0xf9, 0x16, 0x4e, 0x5e, 0xa1, 0x6a, 0x0f,
	0x27, 0xf9, 0xac, 0x2f, 0xb9, 0x31, 0xb6, 0x4d, 0x07, 0x34, 0x4d, 0x07, 0xe4, 0x05, 0x1c, 0x5b,
	0xc7, 0x1a, 0x62, 0x7a, 0x6b, 0xee, 0x54, 0x52, 0xb5, 0xc9, 0x9c, 0x9c, 0xed, 0x36, 0x69, 0x2a,
	0xec, 0xcc, 0x7b, 0xb3, 0x4d, 0x66, 0x49, 0x27, 0xde, 0x93, 0xff, 0x14, 0x20, 0xc2, 0x35, 0xee,
	0xc8, 0x0f, 0xdb, 0x8d, 0x6b, 0x1d, 0x60, 0x03, 0xf2, 0x15, 0x1c, 0x5a, 0x79, 0xee, 0x5c, 0x69,
	0xe9, 0x33, 0x5c, 0x78, 0xab, 0xd1, 0x5e, 0x4d, 0x98, 0x1e, 0x9d, 0x58, 0x85, 0xcd, 0x71, 0xb9,
	0xdb, 0xc9, 0xb3, 0x74, 0xd8, 0x4f, 0xd3, 0x01, 0x79, 0x6e, 0x7a, 0x14, 0xe1, 0x9a, 0x5f, 0xa2,
	0xb8, 0x76, 0x1f, 0x49, 0xb7, 0xd8, 0xbf, 0x96, 0xdb, 0x3c, 0x3a, 0x78, 0xf9, 0xe9, 0xfb, 0x4f,
	0x36, 0xf9, 0xf2, 0xa7, 0x07, 0x2b, 0xb1, 0x5d, 0x3e, 0xb4, 0x39, 0x0f, 0xcc, 0x6f, 0xd6, 0x87,
	0xe6, 0xef, 0xf9, 0xd8, 0xfc, 0x7b, 0xfc, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x31, 0x9a, 0xcb,
	0xe1, 0xd0, 0x0a, 0x00, 0x00,
}
